server:
  port: 8081

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/iom_db?serverTimezone=UTC
      username: root
      password: 456852
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
  mvc:
    view:
      prefix: /resources/templates/
    pathmatch:
      matching-strategy: ant_path_matcher

prometheus:
  url: http://192.168.241.17:9090/api/v1/

logging:
  level:
    com.gxzygygs.iom: debug
