server:
  port: 8081

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/iom_db?serverTimezone=UTC
      username: root
      password: 456852

mybatis-plus:
  global-config:
    db-config:
      table-prefix: iom_
