server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/iom_db?serverTimezone=UTC
      username: root
      password: 456852
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
  mvc:
    view:
      prefix: /resources/templates/
    pathmatch:
      matching-strategy: ant_path_matcher

shiro-redis:
  redis-manager:
    host: 127.0.0.1:6379
    password:
    deploy-model: standalone

  cache-manager:
    #redis过期时间
    expire: 1800


#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: iom_


